# Generated by Django 3.1.4 on 2021-02-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='btc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
